apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: toolbox
  namespace: toolbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: toolbox
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
